### ISSUE TITLE
Brand icon font missing for Docker

### ISSUE THREAD

**Issue by damianog** [SecretumTheme/secretum#1]
Hi

I am using this theme in my blog and I am trying to add to a nav menu on footer with the links to several cloud resources like Github and others by class attribute "fi-<brand>". I like to add the Brand icon for Docker but in Foundation Icon that is the font icons used in Secretum theme is not available. Any way to add custom fonts to cdn resources like font awesome or others?

**Comment by SecretumTheme** [comment]
Hello,
You can use the Better Font Awesome plugin. Once activated, all currently used theme icons will switch from Foundation Icons to Font Awesome icons. Be sure to clear your cache to ensure the icons switch.

https://wordpress.org/plugins/better-font-awesome/

Let me know if you have any other questions.

**Comment by damianog** [comment]
HI @SecretumTheme thanks for the tip, I have installed the official Font Awesome plugin

https://wordpress.org/plugins/font-awesome/

and it runs without problem
