### ISSUE TITLE
Google Search Console reporting breadcrumblist errors with this theme

### ISSUE THREAD

**Issue by davemabe** [SecretumTheme/secretum#2]
Google Search console is reporting:

Missing field "position"
Either "name" or "item.name" should be specified

Here's the link it gives to the documentation on Breadcrumbs:
https://developers.google.com/search/docs/data-types/breadcrumb

**Comment by SecretumTheme** [comment]
Hey @davemabe 
Thanks for notice, I've pushed out an update with corrections on both issues. Hopefully all is good now.
