### ISSUE TITLE
Page shift with larger content

### ISSUE THREAD

**Issue by schiroky** [SecretumTheme/secretum#3]
Hi,

found a problem with the theme: when the content exeeds a spcial ammount of hight, the menu, content etc. is shifting several steps left/right; and only on 4k window screen of the browser. Shrinking brower menu is a workaround at moment.

Would be greate to have this addressed/fixed in next release.

Best Regards,

Claus Schiroky

**Comment by ChrisWinters** [comment]
Hello Claus,
I'm attempting to replicate this issue on Linux chrome/firefox emulating the screen size 4096 X 2160. I'm unable to produce any oddities on this end, not that one doesn't exist though.

What OS / browser are you using? Is it possible you can take a screenshot for me and send over the url you're having this issue on? If you would like to keep the information private you can email it to me at chrisw at null dot net.

Chris

**Comment by schiroky** [comment]
Hi Chris,

please find a small recording of the problem here: https://www.schiroky.com/WebIssue.mp4

Best Regards,

Claus Schiroky



Von: Chris Winters <notifications@github.com>
Gesendet: Dienstag, 18. Februar 2020 18:33
An: SecretumTheme/secretum <secretum@noreply.github.com>
Cc: Claus Schiroky <claus@schiroky.com>; Author <author@noreply.github.com>
Betreff: Re: [SecretumTheme/secretum] Page shift with larger content (#3)


Hello Claus,
I'm attempting to replicate this issue on Linux chrome/firefox emulating the screen size 4096 X 2160. I'm unable to produce any oddities on this end, not that one doesn't exist though.

What OS / browser are you using? Is it possible you can take a screenshot for me and send over the url you're having this issue on? If you would like to keep the information private you can email it to me at chrisw at null dot net.

Chris

**Comment by ChrisWinters** [comment]
@schiroky Sorry for the delay, things got a little crazy as you know.

After watching the video I noticed that the shift is due to the scrollbar appearing, due to the page having content that can be scrolled verses the other pages not having content.

Stay safe and thanks for using Secretum!

~Chris

**Comment by schiroky** [comment]
Hi,

Oh man, I must have been blind. Simply did not realize that tiny detail.

Thank you

Best Regards,

Claus Schiroky
