### ISSUE TITLE
WooCommerce templates out of date

### ISSUE THREAD

**Issue by billc108** [SecretumTheme/secretum#4]
secretum/woocommerce/global/quantity-input.php version 3.6.0 is out of date. The core version is 4.0.0,

secretum/woocommerce/myaccount/form-login.php version 3.6.0 is out of date. The core version is 4.1.0,

Please update, test, release new version.  
Thanks.

**Comment by SecretumTheme** [comment]
Hello @billc108 
Secretum Theme has been updated at both GitHub and WordPress.

You can force the update by accessing wp-admin/update-core.php

Thanks for using Secretum and enjoy!
